// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkgz6EK0134BPf1eACksgTZILXYJ4-BiU',
    appId: '1:977232070432:web:872a402b070af630aff945',
    messagingSenderId: '977232070432',
    projectId: 'flutter-prep-31b9e',
    authDomain: 'flutter-prep-31b9e.firebaseapp.com',
    databaseURL: 'https://flutter-prep-31b9e-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-31b9e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV0cbCrllQbTYZ-EeoioerqMTVfxVk7YU',
    appId: '1:977232070432:android:4e42cf2a7c6f6f00aff945',
    messagingSenderId: '977232070432',
    projectId: 'flutter-prep-31b9e',
    databaseURL: 'https://flutter-prep-31b9e-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-31b9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLNg-B4l8VLyeE673uqd-jfiDaiCyXsjM',
    appId: '1:977232070432:ios:c97af30563b16682aff945',
    messagingSenderId: '977232070432',
    projectId: 'flutter-prep-31b9e',
    databaseURL: 'https://flutter-prep-31b9e-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-31b9e.appspot.com',
    iosBundleId: 'com.example.testImagePicker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLNg-B4l8VLyeE673uqd-jfiDaiCyXsjM',
    appId: '1:977232070432:ios:aa981e29bf9a6c78aff945',
    messagingSenderId: '977232070432',
    projectId: 'flutter-prep-31b9e',
    databaseURL: 'https://flutter-prep-31b9e-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-31b9e.appspot.com',
    iosBundleId: 'com.example.testImagePicker.RunnerTests',
  );
}
